blueprint:
  name: Cleanup
  description: "Konstate Nachricht zur erinnerung der Kinder daran aufzuräumen."
  domain: automation
  source_url: https://github.com/FourtyNos/HomeAssistant/blob/main/Blueprints/Cleanup.yaml
  input:
    schalter1:
      name: "Schalter"
      description: Der eingabe Switch der die automation Triggert und am laufen hält. (ein "Helfer")
      selector:
        entity:
          filter:
            - domain: input_boolean
            - device_class: input_boolean
  
    target_media:
      name: "Wiedergabegerät"
      description: Das Gerät welches die wiedergabe machen soll
      selector:
          entity:
            filter:
            - domain: media_player

trigger:
  platform: state
  entity_id: !input schalter1
  from: "off"
  to: "on"

condition: 

action:
  - repeat:
      sequence:
        - service: tts.cloud_say
          metadata: {}
          data:
            cache: false
            entity_id: !input target_media
            message: |
              {{ [ 
               'Ihr Sollt das Zimmer aufräumen!!',
               'Aufräumen, los!', 
               'macht Endlich, los!',
               'was sollt ihr tun? aufräumen!',
               'macht es endlich los!',
               'Räumt auf!',
               'hört auf zu spielen',
               'bleibt endlich im Zimmer',
               'bleibt in Zimmer und räumt auf',
               'Räumt jetzt weiter auf',
               'Kinder - aufräumen los!'
                ] | random }}
      until:
        - condition: state
          entity_id: !input schalter1
          state: "off"